version: "3.7"
services:
  app:
    build:
      args:
        user: sen
        uid: 1000
      context: ./
      dockerfile: ./.docker/Dockerfile
    image: senneshop
    container_name: senneshop-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - senneshop

  db:
    image: mysql:8.0
    container_name: senneshop-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: senneshop
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_PASSWORD: sen
      MYSQL_USER: sen
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./.docker/docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - senneshop

  nginx:
    image: nginx:1.17-alpine
    container_name: senneshop-nginx
    restart: unless-stopped
    ports:
      - 8000:82
    volumes:
      - ./:/var/www
      - ./.docker/docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - senneshop




networks:
  senneshop:
    driver: bridge
